services:
  auth-service:
    build:
      context: ./back/auth-service
      dockerfile: Dockerfile
    env_file:
      - ./back/auth-service/.env
    ports:
      - "3001:3001"
    environment:
      - AUTH_PORT=3001
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@auth-db:5432/auth_db?schema=public
      - PRISMA_CLIENT_ENGINE_TYPE=binary
      - PRISMA_CLI_QUERY_ENGINE_TYPE=binary
      # set true if you want to seed on container start
      - PRISMA_SEED=false
    depends_on:
      - auth-db
    volumes:
      - ./back/auth-service:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - app-network

  product-service:
    build:
      context: ./back/product-service
      dockerfile: Dockerfile
    env_file:
      - ./back/product-service/.env
    ports:
      - "3002:3001"
    environment:
      - PRODUCT_PORT=3001
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@product-db:5432/product_db?schema=public
      - PRISMA_CLIENT_ENGINE_TYPE=binary
      - PRISMA_CLI_QUERY_ENGINE_TYPE=binary
      - PRISMA_SEED=false
    depends_on:
      - product-db
    volumes:
      - ./back/product-service:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - app-network

  order-service:
    build:
      context: ./back/order-service
      dockerfile: Dockerfile
    env_file:
      - ./back/order-service/.env
    ports: 
      - "3003:3001"
    environment:
      - ORDER_PORT=3001
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@order-db:5432/order_db?schema=public
      - PRISMA_CLIENT_ENGINE_TYPE=binary
      - PRISMA_CLI_QUERY_ENGINE_TYPE=binary
      - PRISMA_SEED=false
      - KAFKA_BROKER_1=kafka-1:9092
      - KAFKA_BROKER_2=kafka-2:9092
    depends_on:
      - order-db
      - kafka-1
      - kafka-2
    volumes:
      - ./back/order-service:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - app-network

  cart-service:
    build:
      context: ./back/cart-service
      dockerfile: Dockerfile
    env_file:
      - ./back/cart-service/.env
    ports: 
      - "3004:3001"
    environment:
      - CART_PORT=3001
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@cart-db:5432/cart_db?schema=public
      - PRISMA_CLIENT_ENGINE_TYPE=binary
      - PRISMA_CLI_QUERY_ENGINE_TYPE=binary
      - PRISMA_SEED=false
    depends_on:
      - cart-db
    volumes:
      - ./back/cart-service:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - app-network

  inventory-service:
    build:
      context: ./back/inventory-service
      dockerfile: Dockerfile
    env_file:
      - ./back/inventory-service/.env
    ports: 
      - "3005:3001"
    environment:
      - INVENTORY_PORT=3001
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@inventory-db:5432/inventory_db?schema=public
      - PRISMA_CLIENT_ENGINE_TYPE=binary
      - PRISMA_CLI_QUERY_ENGINE_TYPE=binary
      - PRISMA_SEED=false
      - KAFKA_BROKER_1=kafka-1:9092
      - KAFKA_BROKER_2=kafka-2:9092
    depends_on:
      - inventory-db
      - kafka-1
      - kafka-2
    volumes:
      - ./back/inventory-service:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - app-network

  delivery-service:
    build:
      context: ./back/delivery-service
      dockerfile: Dockerfile
    env_file:
      - ./back/delivery-service/.env
    ports: 
      - "3006:3001"
    environment:
      - DELIVERY_PORT=3001
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@delivery-db:5432/delivery_db?schema=public
      - PRISMA_CLIENT_ENGINE_TYPE=binary
      - PRISMA_CLI_QUERY_ENGINE_TYPE=binary
      - PRISMA_SEED=false
    depends_on:
      - delivery-db
    volumes:
      - ./back/delivery-service:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - app-network

  rating-service:
    build:
      context: ./back/rating-service
      dockerfile: Dockerfile
    env_file:
      - ./back/rating-service/.env
    ports: 
      - "3007:3001"
    environment:
      - RATING_PORT=3001
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@rating-db:5432/rating_db?schema=public
      - PRISMA_CLIENT_ENGINE_TYPE=binary
      - PRISMA_CLI_QUERY_ENGINE_TYPE=binary
      - PRISMA_SEED=false
    depends_on:
      - rating-db
    volumes:
      - ./back/rating-service:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - app-network

  payment-service:
    build:
      context: ./back/payment-service
      dockerfile: Dockerfile
    env_file:
      - ./back/payment-service/.env
    ports: 
      - "3008:3001"
    environment:
      - PAYMENT_PORT=3001
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@payment-db:5432/payment_db?schema=public
      - PRISMA_CLIENT_ENGINE_TYPE=binary
      - PRISMA_CLI_QUERY_ENGINE_TYPE=binary
      - PRISMA_SEED=false
      - KAFKA_BROKER_1=kafka-1:9092
      - KAFKA_BROKER_2=kafka-2:9092
    depends_on:
      - payment-db
      - kafka-1
      - kafka-2
    volumes:
      - ./back/payment-service:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - app-network

  auth-db:
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=auth_db
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - app-network

  product-db:
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=product_db
    volumes:
      - product-db-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - app-network

  order-db:
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=order_db
    volumes:
      - order-db-data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    networks:
      - app-network

  cart-db:
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=cart_db
    volumes:
      - cart-db-data:/var/lib/postgresql/data
    ports:
      - "5437:5432"
    networks:
      - app-network

  inventory-db:
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=inventory_db
    volumes:
      - inventory-db-data:/var/lib/postgresql/data
    ports:
      - "5438:5432"
    networks:
      - app-network

  delivery-db:
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=delivery_db
    volumes:
      - delivery-db-data:/var/lib/postgresql/data
    ports:
      - "5439:5432"
    networks:
      - app-network

  rating-db:
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=rating_db
    volumes:
      - rating-db-data:/var/lib/postgresql/data
    ports:
      - "5440:5432"
    networks:
      - app-network

  payment-db:
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=payment_db
    volumes:
      - payment-db-data:/var/lib/postgresql/data
    ports:
      - "5441:5432"
    networks:
      - app-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - app-network

  kafka-1:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - app-network

  kafka-2:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - app-network

volumes: 
  auth-db-data:
  product-db-data:
  order-db-data:
  cart-db-data:
  inventory-db-data:
  delivery-db-data:
  rating-db-data:
  payment-db-data:

networks:
  app-network:
    driver: bridge