- name: Install Java 21 and dependencies
  apt:
    name:
      - fontconfig
      - openjdk-21-jre
    state: present
    update_cache: yes

- name: Create keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Clean up any old Jenkins sources
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/jenkins.list
    state: absent

- name: Download Jenkins GPG key (Official Doc)
  ansible.builtin.get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2026.key
    dest: /etc/apt/keyrings/jenkins-keyring.asc
    mode: '0644'
    force: yes

- name: Add Jenkins repository (Official Doc)
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
    state: present
    filename: jenkins
    update_cache: yes

- name: Install Jenkins
  apt:
    name: jenkins
    state: present

- name: Start and enable Jenkins
  service:
    name: jenkins
    state: started
    enabled: yes

- name: Add jenkins user to docker group
  user:
    name: jenkins
    groups: docker
    append: yes

- name: Restart Jenkins
  service:
    name: jenkins
    state: restarted
