export const ORDER_EVENTS = {
  ORDER_CREATED_ONLINE_PAYMENT: 'ORDER_CREATED_ONLINE_PAYMENT',
  ORDER_CREATED_CASH_ON_DELIVERY: 'ORDER_CREATED_CASH_ON_DELIVERY',
} as const;

export type OrderEventType = typeof ORDER_EVENTS[keyof typeof ORDER_EVENTS];
